=== spiana/serpics/serpics/admin/src/main/resources/META-INF/amc.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="navigator-definition" 
xmlns="" 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:msdata="urn:schemas-microsoft-com:xml-msdata"
targetNamespace="http://www.serpicsframework.org/schema/smc">
  <xs:element name="navigator-definition" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="navigator">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="navigator-item" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="allow-child" type="xs:boolean" />
                  <xs:attribute name="bean" type="xs:string" />
                  <xs:attribute name="name" type="xs:string" />
                  <xs:attribute name="parent" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== spiana/serpics/serpics/admin/src/main/resources/META-INF/admin-amc.xml
<?xml version="1.0" encoding="UTF-8"?>
<navigator-definition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"	xmlns="" xsi:schemaLocation="amc.xsd">

<!-- da definire come fare il bind con i bean -->
	<navigator name="mainNav">
		<navigator-item 	allow-child="true"  	bean=""					name="admin" 		parent="" />
		<navigator-item 	allow-child="false" 	bean="" 				name="users" 		parent="admin" />
		<navigator-item 	allow-child="false" 	bean="" 				name="currency" 	parent="admin" />
		<navigator-item 	allow-child="false" 	bean="" 				name="userReg" 		parent="admin" />		
		<navigator-item 	allow-child="false" 	bean="" 				name="relation" 	parent="admin" />		
		<navigator-item 	allow-child="false" 	bean="" 				name="country" 		parent="admin" />		
		<navigator-item 	allow-child="false" 	bean="" 				name="geocode" 		parent="admin" />		
		<navigator-item 	allow-child="true"  	bean="" 				name="catalog" 		parent="" />	
		<navigator-item 	allow-child="false" 	bean="" 				name="category"		parent="catalog" />
		<navigator-item 	allow-child="false" 	bean="" 				name="product" 		parent="catalog" />
		<navigator-item 	allow-child="false" 	bean="" 				name="featureModel" parent="catalog" />
		<navigator-item 	allow-child="true"  	bean="" 				name="order" 		parent="" />
		<navigator-item 	allow-child="false" 	bean="" 				name="orderEntry" 	parent="order" />	
		<navigator-item 	allow-child="false" 	bean="" 				name="dataEntry"	parent="order" />
		<navigator-item 	allow-child="false" 	bean="" 				name="orderStatus" 	parent="order" />
		<navigator-item 	allow-child="false" 	bean="" 				name="missing" 		parent="order" />
		<navigator-item 	allow-child="false" 	bean="" 				name="cancelled" 	parent="order" />
		<navigator-item 	allow-child="true"  	bean="" 				name="consignement" parent="" />
		<navigator-item 	allow-child="false" 	bean="" 				name="entry" 		parent="consignement" />	
		<navigator-item 	allow-child="false" 	bean="" 				name="dateCreation" parent="consignement" />		
		<navigator-item 	allow-child="true"  	bean="" 				name="wharehouse" 	parent="" />
		<navigator-item 	allow-child="false" 	bean="" 				name="stockId" 		parent="wharehouse" />	
		<navigator-item 	allow-child="false" 	bean="" 				name="stockLevel" 	parent="wharehouse" />
		<navigator-item 	allow-child="false" 	bean="" 				name="inStock" 		parent="wharehouse" />
		<navigator-item 	allow-child="false" 	bean="" 				name="outStock" 	parent="wharehouse" />
		<navigator-item 	allow-child="false" 	bean=""					name="lowStock" 	parent="wharehouse" />						
	</navigator>
	
</navigator-definition>
