=== spiana/serpics/serpics/serpics-smc/src/main/resources/META-INF/smc-navigator.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<xsd:schema
xmlns="http://www.serpicsframework.com/schema/smc-navigator" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns:msdata="urn:schemas-microsoft-com:xml-msdata"
targetNamespace="http://www.serpicsframework.com/schema/smc-navigator">

  <xsd:element name="navigator-definition" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
     <xsd:complexType>
      <xsd:choice minOccurs="1" maxOccurs="1">
        <xsd:element name="navigator" maxOccurs="1" minOccurs="1">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="navigator-item" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:attribute name="allow-child" type="xsd:boolean" default="false" />
                  <xsd:attribute name="bean" type="xsd:string" />
                  <xsd:attribute name="class" type="xsd:string" />
                  <xsd:attribute name="name" type="xsd:string" use="required" />
                  <xsd:attribute name="parent" type="xsd:string" default="" />
                  <xsd:attribute name="roles" type="xsd:string" default="" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="name" type="xsd:string" />
          </xsd:complexType>
        </xsd:element>
      </xsd:choice>
    </xsd:complexType>
 </xsd:element>
 </xsd:schema>

=== spiana/serpics/serpics/serpics-smc/src/main/resources/META-INF/smc-navigator.xml
<?xml version="1.0" encoding="UTF-8"?>
<navigator-definition 
xmlns="http://www.serpicsframework.com/schema/smc-navigator" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"	
xsi:schemaLocation="file:/Users/spiana/git/serpics-code/serpics/admin/src/main/resources/META-INF/smc-navigator.xsd">

	<navigator name="mainNav">
		<navigator-item	allow-child="true"  name="admin" parent="" />
		<navigator-item	allow-child="false" bean="userTableEditor" 	name="users" parent="admin" />
		<navigator-item	allow-child="false" bean="membergroupTableEditor" name="group" 		parent="admin" />
		<navigator-item	allow-child="false" bean="roleTable" name="roles" parent="admin"  roles="ROLE_SUPERUSER" />
		
		<navigator-item	allow-child="true" 	name="catalog" 	parent="" />
		<navigator-item allow-child="false" class="com.serpics.catalog.data.model.Catalog" name="productCatalog" parent="catalog" roles="ROLE_SUPERUSER" />	
		
		<navigator-item allow-child="false" class="com.serpics.catalog.data.model.Catalog2StoreRelation" name="storeCatalog" parent="catalog" />	
		<navigator-item allow-child="false" bean="brandTable" name="brand" parent="catalog" />	
		<navigator-item	allow-child="false" bean="categoryTable" name="category" parent="catalog" />
		<navigator-item allow-child="false" bean="productTable" name="product" parent="catalog" />
		<navigator-item allow-child="false" bean="variantTable" name="variant" parent="catalog" />
		<navigator-item allow-child="false" class="com.serpics.catalog.data.model.Pricelist" name="priceList" parent="catalog" />
		

		<navigator-item allow-child="false" bean="featureModelTable" name="featureModel" parent="catalog" />
		<navigator-item allow-child="false" class="com.serpics.catalog.data.model.CtentryMedia" name="ctentryMedia" parent="catalog" />
		
		<navigator-item allow-child="true" 	name="orders" parent="" />
<!-- 		<navigator-item	allow-child="false" bean="orderMasterTable"	name="order" parent="orders" /> -->
		<navigator-item	allow-child="false"	class="com.serpics.commerce.data.model.Cart" name="cart" parent="orders" />
		<navigator-item	allow-child="false"	bean="orderMasterTable" name="order" parent="orders" />
		<navigator-item	allow-child="false"	class="com.serpics.commerce.data.model.Paymethod" name="payMethod" parent="orders" roles="ROLE_SUPERUSER"/>
		<navigator-item	allow-child="false"	class="com.serpics.commerce.data.model.Paymethodlookup" name="payMethods" parent="orders" />
		
	
		<navigator-item	allow-child="false"	class="com.serpics.commerce.data.model.Shipmode" name="shipmode" parent="orders" roles="ROLE_SUPERUSER"/>
		<navigator-item	allow-child="false"	class="com.serpics.commerce.data.model.Shipmodelookup" name="shipmodeLookup" parent="orders" />
	
		<navigator-item	allow-child="true"  name="system" parent="" />
		<navigator-item allow-child="false" class="com.serpics.base.data.model.Locale" name="locale" parent="system"  roles="ROLE_SUPERUSER" />
		<navigator-item allow-child="false" class="com.serpics.base.data.model.Store" name="store" parent="system"  roles="ROLE_SUPERUSER" />
		
		<navigator-item	allow-child="false" bean="currencyTable" name="currency" parent="system" roles="ROLE_SUPERUSER" />
		<navigator-item	allow-child="false" class="com.serpics.base.data.model.TaxCategory" name="taxcategory" parent="system" roles="ROLE_SUPERUSER" />
		<navigator-item	allow-child="false"	class="com.serpics.base.data.model.BaseAttribute" name="baseAttribute" parent="system" />
		
		<navigator-item allow-child="true" name="geographic" parent="system" roles ="ROLE_SUPERUSER,ROLE_ADMINISTRATOR"/>
		<navigator-item allow-child="false" class="com.serpics.postman.model.TemplateType" name="templatetype" parent="system"  roles="ROLE_SUPERUSER" />
		
		<navigator-item	allow-child="false" bean="countryTable"	name="country" parent="geographic" roles="ROLE_SUPERUSER"/>	
		<navigator-item	allow-child="false" class="com.serpics.base.data.model.Region"	name="region" parent="geographic" roles="ROLE_SUPERUSER"/>
		<navigator-item	allow-child="false" class="com.serpics.base.data.model.District"	name="district" parent="geographic" roles="ROLE_SUPERUSER"/>	
		<navigator-item	allow-child="false" bean="geocodeTable"	name="geocode" parent="geographic" roles ="ROLE_SUPERUSER,ROLE_ADMINISTRATOR"/>
		
		<navigator-item	allow-child="true"  name="mail" parent=""/>
		<navigator-item allow-child="false" class="com.serpics.postman.model.TemplateStore" name="templatestore" parent="mail"  roles="ROLE_SUPERUSER,ROLE_ADMINISTRATOR" />
			
	</navigator>

</navigator-definition>
